apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  namespace: vuln-ns
spec:
  containers:
  - name: root-container
    image: ubuntu:latest
    command: ["sleep", "3600"]
    securityContext:
      privileged: true
  restartPolicy: Never
