apiVersion: v1
kind: Service
metadata:
  name: vuln-web-svc
spec:
  selector:
    app: vuln-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Ou LoadBalancer si cloud
