---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-ssh-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-ssh-pvc
  namespace: vuln-ssh-internal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
