---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-ssh
  namespace: vuln-ssh-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-ssh
  template:
    metadata:
      labels:
        app: vuln-ssh
    spec:
      serviceAccountName: ssh-admin
      containers:
      - name: vuln-ssh
        image: rastasheep/ubuntu-sshd:18.04
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 22
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_PTRACE", "NET_ADMIN"]
          runAsUser: 0
          allowPrivilegeEscalation: true
        env:
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ssh-credentials
              key: password
        command: ["/bin/bash"]
        args:
        - "-c"
        - |
          echo "root:$ROOT_PASSWORD" | chpasswd && \
          /usr/sbin/sshd -D
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      restartPolicy: Always