---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-credentials
  namespace: vuln-ssh-internal
type: kubernetes.io/basic-auth
data:
  username: cm9vdA==        # "root"
  password: cm9vdA==        # "root"
