apiVersion: v1
kind: Service
metadata:
  name: vuln-ssh-svc
  namespace: vuln-ssh-internal
spec:
  selector:
    app: vuln-ssh
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: ClusterIP  # Internal-only access